Azure/AKS

preview_regions.md

Thanks saudas

---

.github/issue_template.md

Update issue template to direct service availability issues to Azure support.

github(issues): update issue template

---

examples/vnet/00-README.md
examples/vnet/01-aks-vnet.json
examples/vnet/02-aks-custom-vnet.json

Example ARM template which demonstrates the ability to use an existing VNet and custom IP address ranges in AKS.
Refs #27 
Closes #301

Examples for using an existing VNet and custom IP addresses for AKS.

---

examples/vnet/00-README.md

The subscription isn't set int he role assignment scope.  Led me to believe there was an issue in the Azure CLI:  https://github.com/Azure/azure-cli/issues/6435

Fix scope line

---

README.md

Added Link For Azure Community on Kubernetes Slack community

Added Link For Kubernetes Slack

---

CHANGELOG.md

Not everyone it is American 🤣 
Moving the dates to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)

Change Dates to be ISO 8601

---

README.md

Change ACS Engine references to AKS Engine.

---

CHANGELOG.md

Release 2019-02-12 - Hotfix Release

---

CHANGELOG.md

Updated 1.9 and 1.10 guidance for Moby CVE

---

CHANGELOG.md

Merge 2019-02-20 Release Notes

---

CHANGELOG.md

Release 2019-03-07: Negative Natty Narwhals

---

previews.md

Updated to note support limits, added instructions and caveats on the CLI install.

Support disclaimer and preview install directions

---

CHANGELOG.md

Fix typo in 1.9 deprecation notice

Fix typo in 1.9 deprecation notice

---

previews.md

Update support policies

---

CHANGELOG.md

This releases code name is "Limpid Legume"

2019-05-13 Release Notes

---

CHANGELOG.md

This PR adds some release notes.

Release notes for May 20th, 2019 AD, first of it's name, mother of changelogs

---

README.md

Clean up readme, update, links, bug guidance, a unicorn

---

CHANGELOG.md
previews.md

2019-06-24

---

CHANGELOG.md

Please enjoy 🍰 and have a 🌮 🎉 
👍 👎

07 08 release notes, happy friday

---

CHANGELOG.md
previews.md

07-22-2019 "Belligerent Bulbasaur"

---

CHANGELOG.md

Contributing: Fix a typo

---

README.md

Updated to include link to AKS Public Office Hours

Updated to include link to AKS Public Office Hours

---

examples/kube-prometheus/README.md
examples/kube-prometheus/alertmanager-secret.yaml
examples/kube-prometheus/kustomization.yaml

Add an example that demonstrates how to install kube-prometheus with AKS specific customizations.

kube-prometheus example

---

examples/kube-prometheus/README.md
examples/kube-prometheus/kustomization.yaml
examples/kube-prometheus/node-exporter-daemonset.yaml

- How-to section w/ dashboard link
- Higher cpu limit for node exporter

kube-prometheus how-to section and manifest update

---

CHANGELOG.md
vhd-notes/aks-ubuntu/AKSUbuntu-1604/2021.02.03.txt
vhd-notes/aks-ubuntu/AKSUbuntu-1804/2021.02.03.txt

Release notes for Jan 31st to Feb 7th. Please review.
https://github.com/Azure/AKS/issues/1314 and https://github.com/Azure/AKS/issues/1621 need to be verified if they work in 1.20.2 can anyone comment on this? 
Do not merge.

add release notes

---

CHANGELOG.md
vhd-notes/aks-ubuntu/AKSUbuntu-1604/2021.02.17.txt
vhd-notes/aks-ubuntu/AKSUbuntu-1804/2021.02.17.txt

Release notes for feb 14th-feb21st

add feb 14th-feb21st release notes

---

CHANGELOG.md
vhd-notes/AKSWindows/2019/17763.2300.211110.txt
vhd-notes/aks-ubuntu/AKSUbuntu-1804/2021.11.06.txt

First version of release notes done on Thurs 11-11 at 5.15 PM PST.

release-notes-2021-11-11

---

CHANGELOG.md
vhd-notes/aks-ubuntu/AKSUbuntu-1804/2021.11.27.txt

With changes added on Friday Dec 3rd 11 AM.

release-notes-dec2nd

---

CHANGELOG.md

Update Gatekeeper release link in changelog

---

CHANGELOG.md
vhd-notes/aks-ubuntu/AKSUbuntu-1804/2022.01.22.txt

Please review 2022-1-27 release notes.

1-27-release-changes

---

.github/workflows/codespell.yml
CHANGELOG.md
examples/vnet/00-README.md

This could prevent spelling issues in CHANGELOG

test: add codespell github actions

---

CHANGELOG.md

03 04 2022

---

CHANGELOG.md

https://msazure.visualstudio.com/CloudNativeCompute/_git/aks-rp/pullrequest/5726979 for details.

Behavior change to empty put following control plane upgrade

---

CHANGELOG.md
vhd-notes/aks-ubuntu/AKSUbuntu-1804/2022.05.04.txt

new changes 5-8

---

CHANGELOG.md

Removing Dupes and NA per discussion in Teams

Remove Dupes and NA

---

CHANGELOG.md
vhd-notes/AKSWindows/2019/17763.3532.221012.txt
vhd-notes/AKSWindows/2022/20348.1129.221012.txt
vhd-notes/aks-ubuntu/AKSUbuntu-1804/2022.10.12.txt

2022-10-17 Release Notes

---

CHANGELOG.md
vhd-notes/AKSMariner/2022.11.02.txt
vhd-notes/AKSMariner/2022.11.12.txt
vhd-notes/aks-ubuntu/AKSUbuntu-1804/2022.11.02.txt
vhd-notes/aks-ubuntu/AKSUbuntu-1804/2022.11.12.txt
vhd-notes/aks-ubuntu/AKSUbuntu-2204/2022.11.02.txt
vhd-notes/aks-ubuntu/AKSUbuntu-2204/2022.11.12.txt

Updated Rel 1127

---

CHANGELOG.md
vhd-notes/AKSMariner/202303.13.0.txt
vhd-notes/aks-ubuntu/AKSUbuntu-1804/202303.13.0.txt
vhd-notes/aks-ubuntu/AKSUbuntu-2204/202303.13.0.txt

Includes releases from 3/5-3/19

release notes for March 19th 2023

---

CHANGELOG.md
vhd-notes/AKSWindows/2019/17763.4131.230315.txt
vhd-notes/AKSWindows/2022/20348.1607.230315.txt
vhd-notes/aks-ubuntu/AKSUbuntu-1804/202303.22.0.txt
vhd-notes/aks-ubuntu/AKSUbuntu-2204/202303.22.0.txt

Release notes for 2023-03-26

---

.github/fabricbot.json

Closes https://github.com/Azure/AKS/issues/3536

fix: Fabric bot uses a typo in automated comment

---

README.md

Update README.md to add Ireland hiring post

---

README.md

Fix broken links in Ireland job post

Update README.md to fix links in Ireland job post

---

.github/policies/resourceManagement.yml

This PR is to test if assigning mentionees works when labelling issues, this will be reverted

Test label 

---

README.md

Adding recently published roles in australia

Add Australia Eng Roles

---

blog/_config.yml

Small updates: 
- added Google Analytics 
- updated image preview for tweets, etc.

Added Google Analytics to Blog

---

CHANGELOG.md

- Host Network NSG control
- IP Based Load Balancer
- Public IP tags

Updates Networking features to 03-31

---

.github/workflows/jekyll-gh-pages.yml
blog/_config.yml
blog/_includes/analytics-providers/google-gtag.html
blog/_pages/404.md
blog/_pages/categories.html
blog/_pages/category-addons.html
blog/_pages/category-developer.html
blog/_pages/category-general.html
blog/_pages/category-networking.html
blog/_pages/category-operations.html
blog/_pages/category-security.html
blog/_pages/home.md
blog/_pages/posts.md
blog/_pages/tags.html
blog/_posts/2024-05-21-aks-past-present-future.md
blog/_posts/2024-05-22-aks-automatic.md
blog/assets/css/main.scss

- Style updates for left nav and text selection
- CI enhancement to add gtag_id at build time
- Fix to update gtag consent based on value in local storage.

Blog updates

---

blog/_includes/analytics-providers/google-gtag.html
blog/_pages/category-add-ons.html
blog/_pages/category-addons.html
blog/_posts/2024-08-02-istio-with-gateway-api.md

fixing category list in istio post, updating addons landing page, and user consent button style update

chore: blog category fix

---

blog/_includes/nav_list
blog/_layouts/categories.html
blog/_layouts/category.html
blog/_pages/category-ai.html

and improve category capitalization in navigation and layout files

chore: adding new ai category for blog

---

examples/cgroups/revert-cgroup-v1.yaml

A bug is causing intermittent failures by not restarting the node.(https://github.com/brunokino/AKS/commit/3148be81d049480f9a4de1870494230ec78097d9)

fix(cgroup): Issue 3890 - fixing a bug in DaemonSet

---

blog/_posts/2025-01-20-annouce-airflow-howto.md

Blog announcing new Apache Airflow on AKS guidance and commercial support via Astro by Astronomer.io powered on Azure by AKS.

Astro on Azure powered by AKS

---

blog/_posts/2025-01-30-kube-resource-orchestrator.md

@matthchr to correct blog formatting

Fixing formatting

---

blog/_posts/2025-04-02-Scaling-Kubernetes-for-AI-and-Data-intensive-Workloads.md

Pavneeta patch 2

---

.github/policies/bugIssueLifecycleManagement.yml
.github/policies/manageAssignees.yml

There is duplicated stale rule in the policy file which leads to unnecessary noise in the repo. Deleted one of the two rules.

Remove duplicated stale bug action.

---

blog/_config.yml
blog/_posts/2025-04-02-Scaling-Kubernetes-for-AI-and-Data-intensive-Workloads.md
blog/_posts/2025-04-11-infiniband-on-aks.md

Categories must be lowercase otherwise it causes issues with category landing page routing.
Tags don't need to be lowercase but should be to keep consistent with others.

fix(blog): updating category and tags to lowercase

---

blog/_pages/webinars.md

docs: May 2025 agenda update

---

LICENSE.MD

Suppress ongoing bot workflow due to missing license file. Added Microsoft-recommended MIT license

Add MIT License to the project

---

blog/_pages/webinars.md

Updated agenda for June 2025

---

CHANGELOG.md

Adding cost-optimized addonscaling to Release notes

cost optimized addonscaling in release notes

---

.github/policies/manageAssignees.yml

Modifications:
- Switch auto-assignment on for all labels (previously some were not assigning).
Additions:
- Add GPU label assignment.

Fix non-assignment for some labels; Added GPU label assignment.

---

blog/_data/authors.yml
blog/_posts/2025-08-15-cli-agent-for-aks.md

- Add Julia and Aritra as authors to the blog
- Fix formatting + links in CLI Agent blog post

Adding authors + fixes to CLI agent blog post

---

CHANGELOG.md

adding hotfix for CAS bug

---

CHANGELOG.md

Added entry for Azure Policy add-on upgrade to v1.13.1 addressing CVE-2025-47907.

Update CHANGELOG.md for Azure Policy upgrade

---

CHANGELOG.md

Added notes on AzL with NCA100 and --os-sku AzureLinux3

Update CHANGELOG with new features 
