CHANGELOG.md
01-31-19 AKS Release Changelog/Notes!! :shipit: 🍰 🌵 🤙
=> 01-31-19 AKS Release Changelog/Notes

.github/issue_template.md
to warn issue filers not to include these Azure identifiers in their issue.
=> Updating issue template

.github/config.yml, .github/lock.yaml, .github/move.yml, .github/stale.yml
- Adds stale.yaml file for hosted https://github.com/probot/stale 
- daysUntilStale: 90
- daysUntilClose: 14
- exempt tags listed in PR
- Adds lock.yaml file for hosted: https://probot.github.io/apps/lock/
- Threads on closed issues will be locked after 90 days
- Adds move.yml for hosted https://probot.github.io/apps/move/
- This allows maintainers to use the `/move to repo` and `/move to owner/repo` to move tickets for another project to that organization/repo (such as aks-engine issues, ACI, and VK)
- Added a set of short-hand targets in pr
- Adds config.yaml for hosted https://github.com/apps/sentiment-bot
- Toxic level set at .7 (non toxic)
- Link to MS OSS Code of conduct, auto tag myself in marked thread
=> Github Task automation PR

previews.md
=> Add Az Support

vhd-notes/AKSWindows/2019/17763.2366.211215.txt, vhd-notes/AKSWindows/2019/17763.2565.220211.txt, vhd-notes/AKSWindows/2019/17763.2686.220309.txt, vhd-notes/AKSWindows/2019/17763.2686.220317.txt, vhd-notes/AKSWindows/2019/17763.2803.220413.txt
The format of the URI's of the Windows KBs was incorrect. Fixing the last 5 months worth.
=> Correcting the URI's for the Windows KBs

.github/workflows/codespell.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

.github/fabricbot.json
updated aks bot to use https://github.com/orgs/Azure/teams/aks-portal/ for tags related to Azure Portal, similar to https://github.com/orgs/Azure/teams/aks-leads and https://github.com/orgs/Azure/teams/aks-pm
=> update portal tags to use github team

CHANGELOG.md
I found several syntax errors in release note (2023-02-26).
I have corrected them and hope you will check them.
Regards,
=> Fix typo in markdown syntax (Release Note 2023-02-26)

examples/cgroups/README.md
=> Better recommendation about JDK and cgroups

CHANGELOG.md
Adding some clarification for http proxy update since the http proxy config has been mutable for quite some time. This change was for allowing update to http proxy urls which is a specific field in the config and required no API changes.
=> Update 09-17 release notes for http proxy update

CHANGELOG.md
Add the missing change about coredns upgrade in 2024-03-31 release.
=> Update CHANGELOG.md to add coredns patch

.github/policies/resourceManagement.yml
Changing policy to label as stale to 21 days: If an issue has been stale for more than 21 days, it gets labelled as stale
Assign to Allen, Aritra and Julia: For issues without a label, it is assigned to three of us to add the right label
=> Changing bot policies

blog/_includes/analytics-providers/google-gtag.html
Users will need to click "Accept" at the bottom of the page for gtag data to be collected. Default consent is set to the following:
```
gtag('consent', 'default', {
'ad_user_data': 'denied',
'ad_personalization': 'denied',
'ad_storage': 'denied',
'analytics_storage': 'denied',
'wait_for_update': 500,
});
```
=> adding consent banner for gtag tracking

.github/policies/resourceManagement.yml
Add more conditions to prevent the bot from tagging the issue owners after the issue get assigned.
=> Stop tagging the owner when issues are assigned

CHANGELOG.md
In AKS release 2024-02-26, For Clusters 1.29 or greater, Retina was released as a default behavior when Azure Monitoring was turned on. This is to update that release with accurate behavior.
=> Update release notes to reflect Retina Defaulting

blog/_data/authors.yml, blog/_posts/2025-01-30-kube-resource-orchestrator.md
Adding blog post about kro co-written with @matthchr from ASO.
/cc @palma21 @chzbrgr71
=> Adding kro blog post

CHANGELOG.md, examples/vnet/00-README.md
Codespell runs on PRs were failing due to issues in the ChangeLog and an example readme.
=> addressed two minor spelling issues causing codespell failures on PRs

.github/policies/bugIssueLifecycleManagement.yml
Based on request from team reviewing the process this PR contains the following changes:
1. When “Fix in Progress” (fixing) label is added to an issue labeled 'bug', send the following message: “Hi there :wave: AKS bot here. Thank you for reporting this bug to the AKS team. This issue has been tagged as the bug fix is currently in progress. When the fix is complete, we will update you with the investigation and fix details.” Do not mark issues with this label as Stale
2. When "Under Investigation" label is added to an issue labeled 'bug', send the following message: “Hi there :wave: AKS bot here. This issue has been tagged as being investigated by the AKS team. Please check back shortly to see if any additional information or actions are needed from you. Thank you!” Do not mark these …
=> Updates to bug handling based on GitHub process review.

blog/_includes/author-profile.html, blog/_includes/page__meta.html, blog/_posts/2025-01-30-kube-resource-orchestrator.md, blog/_posts/2050-08-24-sample-blog-post.md
When creating a blog post with multiple authors you can now use the `authors` front matter element like this
```yaml
---
authors: 
- Author One
- Author Two 
---
```
This will work for single or multiple post authors. The original `author` front matter element for single-author posts will continue to work as well.
=> feat: add support for multiple authors

.github/workflows/jekyll-gh-pages.yml
Avoid unnecessary re-publish if files are changing outside of the blog.
=> Filter blog build workflow to only blog subfolder

CHANGELOG.md
Updated Kata runtime class name, removed Kata-CC pod memory overhead mention.
=> Update CHANGELOG with clarity for Kata notes
